#ifndef CONFIG_H
#define CONFIG_H

#define DirectoryDataBase "D:/QtVit/Qt5.1.0/Tools/QtCreator/bin/TEST/build-untitled-Desktop-Debug/database/dbfile"
#define FILENAME "file"

#define LOGIN_URL "https://www.space-track.org/ajaxauth/login"
#define LOGIN_PARAMETERS "identity=catkiller95@gmail.com&password=catkiller19950214"
#define COOKIE_JAR "cookie"
#define COOKIE_TYPE "cookie"
#define CURL_AGENT "libcurl-agent/1.0"
#define CURL_CERT_TYPE "PEM"
#define CURL_CERT_PATH "D:/QtVit/Qt5.1.0/Tools/QtCreator/bin/TEST/bookingcar.pem"
#define LOAD_TLE_URL "https://www.space-track.org/basicspacedata/query/class/tle_publish/PUBLISH_EPOCH/"
#define LIMIT_LOAD_TLE_STRING "/orderby/PUBLISH_EPOCH%20asc/limit/10/format/tle/metadata/false"
#define WEB_INTER_ERR_MESSAGE "<html>\n<body>\n\t\n\t\t<p><p>You must be logged in to complete this action</p></p>\n\n</body>\n</html>"

#define SELECT_BY_DATE "SELECT * FROM TLE WHERE (DATE = "


// TLE_PARSER_CONSTS

#define TLE_ID_START_POSITION 2
#define TLE_ID_FINISH_POSITION 7

#define TLE_CLASSIFICATION_START_AND_FINISH_POSITION 7

#define TLE_LAUNCH_YEAR_START_POSITION 9
#define TLE_LAUNCH_YEAR_FINISH_POSITION 11

#define TLE_LAUNCH_DATA_START_POSITION 11
#define TLE_LAUNCH_DATA_FINISH_POSITION 14

#define TLE_LAUNCH_TYPE_START_POSITION 14
#define TLE_LAUNCH_TYPE_FINISH_POSITION 17

#define TLE_ERA_START_POSITION 18
#define TLE_ERA_FINISH_POSITION 20

#define TLE_ERA_TYPE_START_POSITION 20
#define TLE_ERA_TYPE_FINISH_POSITION 32

#define TLE_FIRST_DERIVATIVE_START_POSITION 33
#define TLE_FIRST_DERIVATIVE_FINISH_POSITION 43

#define TLE_SECOND_DERIVATIVE_START_POSITION 44
#define TLE_SECOND_DERIVATIVE_FINISH_POSITION 52

#define TLE_FLOW_TYPE_START_POSITION 53
#define TLE_FLOW_TYPE_FINISH_POSITION 61

#define TLE_NUM_TYPE_START_POSITION 64
#define TLE_NUM_TYPE_FINISH_POSITION 68

#define TLE_CHECK_SUM_START_AND_FINISH_POSITION 68

#define TLE_INCLINATION_START_POSITION 8
#define TLE_INCLINATION_FINISH_POSITION 16

#define TLE_INCLINATION_TO_THE_RIGHT_START_POSITION 17
#define TLE_INCLINATION_TO_THE_RIGHT_FINISH_POSITION 25

#define TLE_EXCENTRICITY_START_POSITION 26
#define TLE_EXCENTRICITY_FINISH_POSITION 33

#define TLE_PERIGEE_START_POSITION 34
#define TLE_PERIGEE_FINISH_POSITION 42

#define TLE_MEAN_ANOMALY_START_POSITION 43
#define TLE_MEAN_ANOMALY_FINISH_POSITION 50

#define TLE_FREQUENCY_START_POSITION 52
#define TLE_FREQUENCY_FINISH_POSITION 63

#define TLE_ERA_NUM_START_POSITION 63
#define TLE_ERA_NUM_FINISH_POSITION 68

// END_TLE_PARSER_CONSTS

#endif // CONFIG_H
